import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'MyFrame',
  description: 'Generated by ychmin@gmail.com',
  other: {
      'fc:frame:image': 'http://rcsi.co.kr/wp-content/uploads/2023/06/gabriella-clare-marino-4amU3xpy0I-unsplash-scaled.jpg'
    , 'og:image': 'http://rcsi.co.kr/wp-content/uploads/2023/06/gabriella-clare-marino-4amU3xpy0I-unsplash-scaled.jpg'
    , 'fc:frame': 'vNext' 
    , 'fc:frame:post_url': 'https://farcaster-chi.vercel.app/'
    , 'fc:frame:button:1': 'Confirm'
    , 'fc:frame:button:1:action': 'post'
    , 'fc:frame:button:1:target': '_self'
    , 'fc:frame:button:1:post_url': 'https://farcaster-chi.vercel.app/'
    , 'fc:frame:button:2': 'Cancel'
    , 'fc:frame:button:2:action': 'post_redirect'
    , 'fc:frame:button:2:target': '_blank'
    , 'fc:frame:input:text': 'Enter a message'
    , 'fc:frame:image:aspect_ratio': '1:1'
    , 'fc:frame:state': '{"status":"active","user":"12345"}' 
    , 'og:type': 'website'  // Open Graph type 추가
    , 'og:url': 'https://farcaster-chi.vercel.app/' // URL 메타 태그 추가
    , 'og:title': 'MyFrame' // 제목 추가
    , 'og:description': 'Farcaster-chi 프로젝트 페이지입니다.' // 설명 추가
    , 'og:video': '' // 영상이 있다면 추가 가능 (iframe 대신)

  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  )
}
