import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'MyFrame',
  description: 'Generated by ychmin@gmail.com',
  other: {
      'fc:frame:image': 'MyFrame'
    , 'og:image': 'This is a frame for Farcaster integration.'
    , 'fc:frame': 'vNext' 
    , 'fc:frame:post_url': 'https://example.com/post-signature'
    , 'fc:frame:button:1': 'Confirm'
    , 'fc:frame:button:1:action': 'post'
    , 'fc:frame:button:1:target': '_self'
    , 'fc:frame:button:1:post_url': 'https://example.com/button1-signature'
    , 'fc:frame:button:2': 'Cancel'
    , 'fc:frame:button:2:action': 'post_redirect'
    , 'fc:frame:button:2:target': '_blank'
    , 'fc:frame:input:text': 'Enter a message'
    , 'fc:frame:image:aspect_ratio': '1:1'
    , 'fc:frame:state': '{"status":"active","user":"12345"}' 
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  )
}
